services:
    entity_tracker.resolver.revision:
        class: Hostnet\Component\EntityRevision\Resolver\RevisionResolver
        arguments:
            - "@entity_tracker.provider.annotation_metadata"

    entity_tracker.listener.revision:
        class: Hostnet\Component\EntityRevision\Listener\RevisionListener
        arguments:
            - "@entity_tracker.resolver.revision"
            - "" # factory service id, (configurable)
            - "@logger"
        tags:
            - { name: doctrine.event_listener, event: entityChanged, priority: 16 }
            - { name: doctrine.event_listener, event: postFlush, priority: 20 }
