services:
    entity_tracker.provider.blamable:
        class: Hostnet\Bundle\EntityTrackerBundle\Services\Blamable\DefaultBlamableProvider
        arguments:
            - "@security.token_storage"
            - "" # It is being injected by the Extension
